update  t_corework set c_initiator='jiangtx' where c_task_num='JS004-0000000473';
update t_task set c_initiator='jiangtx', c_initiatorname='姜田先' c_workid=(select c_id from t_corework where c_task_num='JS004-0000000473') and c_parent_id='-1';
update t_task_relations set c_userid='jiangtx',c_username='姜田先' where c_taskid=(select c_id from t_task where c_workid=(select c_id from t_corework where c_task_num='JS004-0000000473') and c_parent_id='-1') and c_type=1;
update  t_corework set c_initiator='jiangtx' where c_task_num='JS004-0000000471';
update t_task set c_initiator='jiangtx', c_initiatorname='姜田先' c_workid=(select c_id from t_corework where c_task_num='JS004-0000000471') and c_parent_id='-1';
update t_task_relations set c_userid='jiangtx',c_username='姜田先' where c_taskid=(select c_id from t_task where c_workid=(select c_id from t_corework where c_task_num='JS004-0000000471') and c_parent_id='-1') and c_type=1;
update  t_corework set c_initiator='jiangtx' where c_task_num='JS004-0000000470';
update t_task set c_initiator='jiangtx', c_initiatorname='姜田先' c_workid=(select c_id from t_corework where c_task_num='JS004-0000000470') and c_parent_id='-1';
update t_task_relations set c_userid='jiangtx',c_username='姜田先' where c_taskid=(select c_id from t_task where c_workid=(select c_id from t_corework where c_task_num='JS004-0000000470') and c_parent_id='-1') and c_type=1;
update  t_corework set c_initiator='jiangtx' where c_task_num='JS004-0000000469';
update t_task set c_initiator='jiangtx', c_initiatorname='姜田先' c_workid=(select c_id from t_corework where c_task_num='JS004-0000000469') and c_parent_id='-1';
update t_task_relations set c_userid='jiangtx',c_username='姜田先' where c_taskid=(select c_id from t_task where c_workid=(select c_id from t_corework where c_task_num='JS004-0000000469') and c_parent_id='-1') and c_type=1;
update  t_corework set c_initiator='baojb' where c_task_num='JS004-0000000468';
update t_task set c_initiator='baojb', c_initiatorname='包建斌' c_workid=(select c_id from t_corework where c_task_num='JS004-0000000468') and c_parent_id='-1';
update t_task_relations set c_userid='baojb',c_username='包建斌' where c_taskid=(select c_id from t_task where c_workid=(select c_id from t_corework where c_task_num='JS004-0000000468') and c_parent_id='-1') and c_type=1;
update  t_corework set c_initiator='jiangtx' where c_task_num='JS004-0000000466';
update t_task set c_initiator='jiangtx', c_initiatorname='姜田先' c_workid=(select c_id from t_corework where c_task_num='JS004-0000000466') and c_parent_id='-1';
update t_task_relations set c_userid='jiangtx',c_username='姜田先' where c_taskid=(select c_id from t_task where c_workid=(select c_id from t_corework where c_task_num='JS004-0000000466') and c_parent_id='-1') and c_type=1;
update  t_corework set c_initiator='jiangtx' where c_task_num='JS004-0000000465';
update t_task set c_initiator='jiangtx', c_initiatorname='姜田先' c_workid=(select c_id from t_corework where c_task_num='JS004-0000000465') and c_parent_id='-1';
update t_task_relations set c_userid='jiangtx',c_username='姜田先' where c_taskid=(select c_id from t_task where c_workid=(select c_id from t_corework where c_task_num='JS004-0000000465') and c_parent_id='-1') and c_type=1;
update  t_corework set c_initiator='zhoulq' where c_task_num='JS004-0000000402';
update t_task set c_initiator='zhoulq', c_initiatorname='周立芹' c_workid=(select c_id from t_corework where c_task_num='JS004-0000000402') and c_parent_id='-1';
update t_task_relations set c_userid='zhoulq',c_username='周立芹' where c_taskid=(select c_id from t_task where c_workid=(select c_id from t_corework where c_task_num='JS004-0000000402') and c_parent_id='-1') and c_type=1;
update  t_corework set c_initiator='jiangtx' where c_task_num='JS004-0000000401';
update t_task set c_initiator='jiangtx', c_initiatorname='姜田先' c_workid=(select c_id from t_corework where c_task_num='JS004-0000000401') and c_parent_id='-1';
update t_task_relations set c_userid='jiangtx',c_username='姜田先' where c_taskid=(select c_id from t_task where c_workid=(select c_id from t_corework where c_task_num='JS004-0000000401') and c_parent_id='-1') and c_type=1;
update  t_corework set c_initiator='duchh' where c_task_num='JS004-0000000400';
update t_task set c_initiator='duchh', c_initiatorname='杜长浩' c_workid=(select c_id from t_corework where c_task_num='JS004-0000000400') and c_parent_id='-1';
update t_task_relations set c_userid='duchh',c_username='杜长浩' where c_taskid=(select c_id from t_task where c_workid=(select c_id from t_corework where c_task_num='JS004-0000000400') and c_parent_id='-1') and c_type=1;
update  t_corework set c_initiator='jiangtx' where c_task_num='JS004-0000000396';
update t_task set c_initiator='jiangtx', c_initiatorname='姜田先' c_workid=(select c_id from t_corework where c_task_num='JS004-0000000396') and c_parent_id='-1';
update t_task_relations set c_userid='jiangtx',c_username='姜田先' where c_taskid=(select c_id from t_task where c_workid=(select c_id from t_corework where c_task_num='JS004-0000000396') and c_parent_id='-1') and c_type=1;
update  t_corework set c_initiator='duchh' where c_task_num='JS004-0000000395';
update t_task set c_initiator='duchh', c_initiatorname='杜长浩' c_workid=(select c_id from t_corework where c_task_num='JS004-0000000395') and c_parent_id='-1';
update t_task_relations set c_userid='duchh',c_username='杜长浩' where c_taskid=(select c_id from t_task where c_workid=(select c_id from t_corework where c_task_num='JS004-0000000395') and c_parent_id='-1') and c_type=1;
update  t_corework set c_initiator='jiangtx' where c_task_num='JS004-0000000393';
update t_task set c_initiator='jiangtx', c_initiatorname='姜田先' c_workid=(select c_id from t_corework where c_task_num='JS004-0000000393') and c_parent_id='-1';
update t_task_relations set c_userid='jiangtx',c_username='姜田先' where c_taskid=(select c_id from t_task where c_workid=(select c_id from t_corework where c_task_num='JS004-0000000393') and c_parent_id='-1') and c_type=1;
